[env]
TERM = "xterm-256color"

[font]
size = 7

[window]
opacity = 0
dynamic_padding = true

[font.bold]
family = "Ubuntu Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Ubuntu Mono Nerd Font"
style = "Regular"
